version: '3'

services:
  mongo:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - '27017:27017'

  counsily-api:
    image: ankitech/counsilyapi
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3